TK4/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import transaksi.urls as transaksi
from transaksi import views
import login.urls as login
from login import views
import laporan.urls as laporan
from laporan import views
import pengguna.urls as pengguna
from pengguna import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^transaksi/', include(('transaksi.urls', 'transaksi'), namespace='transaksi')),
    url(r'^', include(('login.urls', 'login'), namespace='login')),
    url(r'^laporan/', include(('laporan.urls', 'laporan'), namespace='laporan')), 
    url(r'^pengguna/', include(('pengguna.urls', 'pengguna'), namespace='pengguna')),
    # url(r'^daftar_penyewa/', include(('pengguna.urls', 'daftar_penyewa'), namespace='pengguna')),   
    # url(r'^daftar_pemilik/', include(('pengguna.urls', 'daftar_pemilik'), namespace='pengguna')),   
    # url(r'^daftar_staff/', include(('pengguna.urls', 'daftar_staff'), namespace='daftar_staff')),   
    url(r'^lukisan/', include(('lukisan.urls', 'lukisan'), namespace='lukisan')),   
]

laporan/urls.py
from django.conf.urls import url
from django.urls import path
from .views import list_laporan
from django.conf.urls.static import static
from django.conf import settings

#url for app

app_name = 'laporan'
urlpatterns = [
    path('', list_laporan, name='listlaporan')
]

login/urls.py
from django.urls import path
from django.conf.urls import url
from .views import index
from django.conf.urls.static import static
from django.conf import settings

app_name = 'login'
urlpatterns = [
    path('', index, name='index')
]

lukisan/urls.py
from django.conf.urls import url
from django.urls import path
from .views import *
from django.conf.urls.static import static
from django.conf import settings


app_name = 'lukisan'
urlpatterns = [
    path('', lukisan, name='lukisan')
]

mysite/mysite/urls.py
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

pengguna/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'pengguna'
urlpatterns = [
    path('daftar_penyewa/', views.daftar_penyewa, name='daftar-penyewa'),
    path('daftar-pemilik/', views.daftar_pemilik, name='daftar-pemilik'),
    path('daftar-staff/', views.daftar_staff, name='daftar-staff')
]  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

transaksi/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'transaksi'
urlpatterns = [
    path('riwayat-sewa/', views.riwayat_sewa, name='riwayat-sewa'),
    path('riwayat-fee/', views.riwayat_fee, name='riwayat-fee'),
    path('mitra-bank/', views.mitra_bank, name='mitra-bank')
]  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

laporan/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

login/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

lukisan/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

pengguna/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

transaksi/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

laporan/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Create your views here.

def list_laporan(request):
	return render(request, 'daftar_laporan.html')

login/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render

# Create your views here.
def index(request):
	return render(request, 'home.html')

lukisan/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Create your views here.

def lukisan(request):
	return render(request, 'lukisan.html')

pengguna/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Create your views here.

def daftar_penyewa(request):
	return render(request, 'daftar_penyewa.html')
def daftar_pemilik(request):
	return render(request, 'daftar_pemilik.html')
def daftar_staff(request):
	return render(request, 'daftar_staff.html')

transaksi/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, reverse
from django.http import HttpResponse, HttpResponseRedirect

from django.shortcuts import render

# Create your views here.
def riwayat_sewa(request):
	return render(request, 'transaksi-sewa.html')

def riwayat_fee(request):
	return render(request, 'transaksi-fee.html')

def mitra_bank(request):
	return render(request, 'transaksi-mitra.html')

laporan/templates/daftar_laporan.html
{% extends 'base.html' %}

{% block subtitle %} Masuk {% endblock %}

{% block content %}
 <div class="py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <form class="form-inline">
            <div class="input-group">
            </div>
          </form>
        </div>
      </div>
    </div>
    <div class="container">
      <table class="table table-hover">
        <thead>
          <tr>
            <th scop="col">Tipe_Anggota <i class="fa fa-sort-asc"></i></th>
            <th scop="col">Lukisan</th>
            <th scop="col">Keterlambatan</th>
            <th scop="col">Pengembalian</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <tr class="tr-hoverisible">
            <th scope="row">Penyewa</th>
            <td>Starry_Night</td>
            <td>None</td>
            <td>02/02/19</td>
            
          </tr>
          <tr class="tr-hoverisible">
            <th scope="row">Pemilik</th>
            <td>Screaming_Man</td>
            <td>None</td>
            <td>02/02/19</td>
            
          </tr>
        </tbody>
      </table>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <ul class="pagination">
          </ul>
        </div>
      </div>
    </div>
  </div>


{% endblock %}

login/templates/home.html
{% extends "base.html" %}
{% load static %}
{% block title %}Transaksi{% endblock %}
{% block content %}
<style>
    body {
      background-image: url("https://images.wallpaperscraft.com/image/acrylic_paint_stain_137240_3840x2400.jpg");
    }
    h1 {
      color: white;
      text-align: center;
      margin: 0;
      position: absolute;
      top: 50%;
      left: 50%;
      -ms-transform: translate(-50%, -50%);
      transform: translate(-50%, -50%);
    }
</style>
<h1 style="font-size:5vw;">Masterpieces Ltd.</h1>


{% endblock %}

lukisan/templates/lukisan.html
{% extends "base.html" %}
{% load static %}
{% block title %}Daftar Penyewa{% endblock %}
{% block content %}
<link href="{% static 'css/transaksi.css' %}" rel="stylesheet"></link>

<!-- Page Content -->
<div class="container">
    <div class="card border-0 shadow my-5">
        <div class="card-body p-5">
            <h1>DAFTAR LUKISAN</h1>
            
            <br>
            <table id ="table2" class="table text-center table-hover ">
              <thead class="thead-dark">
                <tr>
                  <th scope="col">ID Lukisan</th>
                  <th scope="col">Nama Lukisan</th>
                  <th scope="col">Tema Lukisan</th>
                  <th scope="col">Harga / bulan</th>
                  <th scope="col">Tahun</th>
                  <th scope="col">ID Pemilik</th>
                </tr>
              </thead>
              <tbody>
                {% for j in lukisan %}
                <tr>
                  <td>{{j.0}}</td>
                  <td>{{j.1}}</td>
                  <td>{{j.2}}</td>
                  <td>{{j.3}}</td>
                  <td>{{j.4}}</td>
                  <td>{{j.5}}</td>
                </tr>
               {% endfor %}
              </tbody>
            </table>

        
        </div>
    </div>
</div>

{% endblock %}

pengguna/templates/daftar_pemilik.html
{% extends "base.html" %}
{% load static %}
{% block title %}Daftar Penyewa{% endblock %}
{% block content %}
<link href="{% static 'css/transaksi.css' %}" rel="stylesheet"></link>

<!-- Page Content -->
<div class="container">
    <div class="card border-0 shadow my-5">
        <div class="card-body p-5">
            <h1>DAFTAR PEMILIK</h1>
            
            <br>
            <table id ="table2" class="table text-center table-hover ">
              <thead class="thead-dark">
                <tr>
                  <th scope="col">ID Pelanggan</th>
                  <th scope="col">No. KTP</th>
                  <th scope="col">Nama</th>
                  <th scope="col">Alamat</th>
                  <th scope="col">Tanggal Lahir</th>
                  <th scope="col">No. HP</th>
                  <th scope="col">Email</th>
                  <th scope="col">Pekerjaan</th>
                  <th scope="col">Kategori</th>
                </tr>
              </thead>
              <tbody>
                {% for j in transaksi %}
                <tr>
                  <td>{{j.0}}</td>
                  <td>{{j.1}}</td>
                  <td>{{j.2}}</td>
                  <td>{{j.3}}</td>
                  <td>{{j.4}}</td>
                  <td>{{j.5}}</td>
                </tr>
               {% endfor %}
              </tbody>
            </table>

        
        </div>
    </div>
</div>

{% endblock %}

pengguna/templates/daftar_penyewa.html
{% extends "base.html" %}
{% load static %}
{% block title %}Daftar Penyewa{% endblock %}
{% block content %}
<link href="{% static 'css/transaksi.css' %}" rel="stylesheet"></link>

<!-- Page Content -->
<div class="container">
    <div class="card border-0 shadow my-5">
        <div class="card-body p-5">
            <h1>DAFTAR PENYEWA</h1>
            
            <br>
            <table id ="table2" class="table text-center table-hover ">
              <thead class="thead-dark">
                <tr>
                  <th scope="col">ID Pelanggan</th>
                  <th scope="col">No. KTP</th>
                  <th scope="col">Nama</th>
                  <th scope="col">Alamat</th>
                  <th scope="col">Tanggal Lahir</th>
                  <th scope="col">No. HP</th>
                  <th scope="col">Email</th>
                  <th scope="col">Pekerjaan</th>
                  <th scope="col">Kategori</th>
                </tr>
              </thead>
              <tbody>
                {% for j in transaksi %}
                <tr>
                  <td>{{j.0}}</td>
                  <td>{{j.1}}</td>
                  <td>{{j.2}}</td>
                  <td>{{j.3}}</td>
                  <td>{{j.4}}</td>
                  <td>{{j.5}}</td>
                </tr>
               {% endfor %}
              </tbody>
            </table>

        
        </div>
    </div>
</div>

{% endblock %}

pengguna/templates/daftar_staff.html
{% extends "base.html" %}
{% load static %}
{% block title %}Daftar Penyewa{% endblock %}
{% block content %}
<link href="{% static 'css/transaksi.css' %}" rel="stylesheet"></link>

<!-- Page Content -->
<div class="container">
    <div class="card border-0 shadow my-5">
        <div class="card-body p-5">
            <h1>DAFTAR STAFF</h1>
            
            <br>
            <table id ="table2" class="table text-center table-hover ">
              <thead class="thead-dark">
                <tr>
                  <th scope="col">ID Pelanggan</th>
                  <th scope="col">No. KTP</th>
                  <th scope="col">Nama</th>
                  <th scope="col">Alamat</th>
                  <th scope="col">Tanggal Lahir</th>
                  <th scope="col">No. HP</th>
                  <th scope="col">Email</th>
                  <th scope="col">Pekerjaan</th>
                  <th scope="col">Kategori</th>
                </tr>
              </thead>
              <tbody>
                {% for j in transaksi %}
                <tr>
                  <td>{{j.0}}</td>
                  <td>{{j.1}}</td>
                  <td>{{j.2}}</td>
                  <td>{{j.3}}</td>
                  <td>{{j.4}}</td>
                  <td>{{j.5}}</td>
                </tr>
               {% endfor %}
              </tbody>
            </table>

        
        </div>
    </div>
</div>

{% endblock %}

transaksi/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Base</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
</head>
<style>
    table, th, td {
        border: 1px solid black;
    }
    .subject{
        font-size: 20px;
        font-family: "Comic Sans MS";
        color: #6650ff;
    }
    .value{
        font-size: 20px;
        font-family: "Roboto", "Lucida Grande", Verdana, Arial, sans-serif;
        color: #ff102c;
    }
</style>
<body style="background-color: lightgray">
    <div class="container-fullwidth">
        <nav class="navbar navbar-default navbar-expand-lg navbar-light bg-light">
          <a class="navbar-brand" href="/">Home</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              
              <li class="nav-item" >
                <a class="nav-link" href="/lukisan/">Lukisan</a>
              </li>
			        <li class="nav-item" >
                <a class="nav-link" href="/laporan/">Laporan</a>
              </li>
              
            </ul>
            <div class="dropdown">
              <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                Pengguna
              </button>
              <div class="dropdown-menu">
                <!-- <a class="dropdown-item" href="/daftar_penyewa/"">Daftar Penyewa</a>
                <a class="dropdown-item" href="/daftar_pemilik/"">Daftar Pemilik</a>
                <a class="dropdown-item" href="/daftar_staff/"">Daftar Staff</a> -->
                <a class="dropdown-item" href="{% url 'pengguna:daftar-pemilik' %}">Daftar Pemilik</a>
                <a class="dropdown-item" href="{% url 'pengguna:daftar-penyewa' %}">Daftar Penyewa</a>
                <a class="dropdown-item" href="{% url 'pengguna:daftar-staff' %}">Daftar Staff</a>
              </div>
            </div>
            
              <div class="dropdown">
                <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                  Transaksi
                </button>
                <div class="dropdown-menu">
                  <a class="dropdown-item" href="{% url 'transaksi:riwayat-sewa' %}">Sewa</a>
                  <a class="dropdown-item" href="{% url 'transaksi:riwayat-fee' %}">Fee</a>
                  <a class="dropdown-item" href="{% url 'transaksi:mitra-bank' %}">Mitra Bank</a>
                </div>
              </div>

          </div>
        </nav>
    </div>
    {% block content %}
    {% endblock %}
</body>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
{% block jquery %}
{% endblock %}
</html>

transaksi/templates/transaksi-fee.html
{% extends "base.html" %}
{% load static %}
{% block title %}Transaksi{% endblock %}
{% block content %}
<link href="{% static 'css/transaksi.css' %}" rel="stylesheet"></link>

<!-- Page Content -->
<div class="container">
    <div class="card border-0 shadow my-5">
        <div class="card-body p-5">
            <h1>RIWAYAT TRANSAKSI</h1>
            <h5 style="text-align: right">TIPE : FEE</h5>
            <br>
            <table id ="table2" class="table text-center table-hover ">
              <thead class="thead-dark">
                <tr>
                  <th scope="col">Tanggal Terima</th>
                  <th scope="col">No. Pelanggan</th>
                  <th scope="col">ID Lukisan</th>
                  <th scope="col">Jumlah disewa</th>
                  <th scope="col">Harga Lukisan</th>
                  <th scope="col">Total FEE</th>
                </tr>
              </thead>
              <tbody>
                {% for j in transaksi %}
                <tr>
                  <td>{{j.0}}</td>
                  <td>{{j.1}}</td>
                  <td>{{j.2}}</td>
                  <td>{{j.3}}</td>
                  <td>{{j.4}}</td>
                  <td>{{j.5}}</td>
                </tr>
               {% endfor %}
              </tbody>
            </table>

        
        </div>
    </div>
</div>

{% endblock %}

transaksi/templates/transaksi-mitra.html
{% extends "base.html" %}
{% load static %}
{% block title %}Transaksi{% endblock %}
{% block content %}
<link href="{% static 'css/transaksi.css' %}" rel="stylesheet"></link>

<!-- Page Content -->
<div class="container">
    <div class="card border-0 shadow my-5">
        <div class="card-body p-5">
            <h1>DAFTAR MITRA BANK</h1>
            <br>
            <table id ="table2" class="table text-center table-hover ">
              <thead class="thead-dark">
                <tr>
                  <th scope="col">Kode</th>
                  <th scope="col">Nama Bank</th>
                </tr>
              </thead>
              <tbody>
                {% for b in mitra_bank %}
                <tr>
                  <td>{{b.0}}</td>
                  <td>{{b.1}}</td>
                </tr>
               {% endfor %}
              </tbody>
            </table>

        
        </div>
    </div>
</div>

{% endblock %}

transaksi/templates/transaksi-sewa.html
{% extends "base.html" %}
{% load static %}
{% block title %}Transaksi{% endblock %}
{% block content %}
<link href="{% static 'css/transaksi.css' %}" rel="stylesheet"></link>

<!-- Page Content -->
<div class="container">
    <div class="card border-0 shadow my-5">
        <div class="card-body p-5">
            <h1>RIWAYAT TRANSAKSI</h1>
            <h5 style="text-align: right">TIPE : SEWA</h5>
            <br>
            <table id ="table2" class="table text-center table-hover ">
              <thead class="thead-dark">
                <tr>
                  <th scope="col">Tanggal Sewa</th>
                  <th scope="col">No. Pelanggan</th>
                  <th scope="col">Jumlah Lukisan</th>
                  <th scope="col">ID Lukisan</th>
                  <th scope="col">Tenor</th>
                  <th scope="col">Lama Sewa</th>
                  <th scope="col">Alamat Tujuan</th>
                  <th scope="col">Ongkir</th>
                  <th scope="col">Total</th>
                  <th scope="col">Tanggal Kembali</th>
                  <th scope="col">Pembayaran</th>
                  <th scope="col">No. Staff</th>
                </tr>
              </thead>
              <tbody>
                {% for i in transaksi %}
                <tr>
                  <td>{{i.0}}</td>
                  <td>{{i.1}}</td>
                  <td>{{i.2}}</td>
                  <td>{{i.3}}</td>
                  <td>{{i.4}}</td>
                  <td>{{i.5}}</td>
                  <td>{{i.6}}</td>
                  <td>{{i.7}}</td>
                  <td>{{i.8}}</td>
                  <td>{{i.9}}</td>
                  <td>{{i.10}}</td>
                  <td>{{i.11}</td>
                </tr>
               {% endfor %}
              </tbody>
            </table>

        
        </div>
    </div>
</div>

{% endblock %}